### ISSUE TITLE
Electron with gtk3 work in progress

### ISSUE THREAD

**Issue by eternal-sorrow** [eternal-sorrow/gentoo-local#1]
Issue to track progress in wrighting electron with gtk3 support. Electron issue: electron/electron#2927

@devurandom, here you are my local overlay with electron ebuild.

- [x] Replace sed calls with patches.
- [x] Port "gentoo-build-fixes" to new sources.

**Comment by eternal-sorrow** [comment]
Current issue is build failure with a lot of "undefined reference to `v8::" errors. Full build log is here http://termbin.com/6rx0

**Comment by devurandom** [comment]
1. That log appears to be incomplete. It contains only the first few lines.
2. Please replace the sed calls with patches - that will make it much easier to review.
3. You dropped several "gentoo-build-fixes" patches, some of which influence the linking against v8. Try to port these patches to the new sources. It's a lot of work tracking down how the code / build system changed in between versions, but I would generally assume that those patches are important. Don't drop them, unless you verified that their changes went upstream.

**Comment by eternal-sorrow** [comment]
here is the full build log http://filebin.ca/2sFtffyE2Xhq/build.log

**Comment by devurandom** [comment]
Thanks. I suggest looking into doing (3) - that seems to be the most likely path right now.

To get this into Gentoo and to get further review, I also suggest doing (2) - it's rather easy, you just run (in the ebuild):
```
cp $f $f.orig
sed ...
diff $f.orig $f > $f.patch
```
You can simply run `ebuild ... prepare` to execute only the `src_prepare()` (and preceding) part(s) of the ebuild. Then you collect those patches from $S, move them into $FILESDIR and reference them from the ebuild, as it is done for the other patches.

**Comment by eternal-sorrow** [comment]
[*] Replace sed calls with patches.
[ ] Port "gentoo-build-fixes" to new sources .

**Comment by devurandom** [comment]
Thanks for the patch!

1. I think that your `toolchain.patch` is basically a new version of `dont-use-sysroot.patch`, i.e. it could be named `dont-use-sysroot-r1.patch`.
2. "Update brightray" still uses `sed` and has no patch.

Have you had a chance to try to port the other patches? Or understand why they were necessary and what parts of these changes already went upstream, if any?

**Comment by eternal-sorrow** [comment]
Build failed, wants re2.h.

**Comment by eternal-sorrow** [comment]
build failed with sreange error:
```
../../third_party/WebKit/Source/platform/image-decoders/png/PNGImageDecoder.cpp: In member function ‘void blink::PNGImageDecoder::headerAvailable()’:
../../third_party/WebKit/Source/platform/image-decoders/png/PNGImageDecoder.cpp:237:103: error: invalid conversion from ‘png_bytep {aka unsigned char*}’ to ‘const char*’ [-fpermissive]
                 setColorProfileAndTransform(profile, profileLength, imageHasAlpha, false /* useSRGB */);
                                                                                                       ^
In file included from ../../third_party/WebKit/Source/platform/image-decoders/png/PNGImageDecoder.h:29:0,
                 from ../../third_party/WebKit/Source/platform/image-decoders/png/PNGImageDecoder.cpp:39:
../../third_party/WebKit/Source/platform/image-decoders/ImageDecoder.h:244:10: note:   initializing argument 1 of ‘void blink::ImageDecoder::setColorProfileAndTransform(const char*, unsigned int, bool, bool)’
     void setColorProfileAndTransform(const char* iccData, unsigned iccLength, bool hasAlpha, bool useSRGB);
          ^
```

**Comment by eternal-sorrow** [comment]
It compiled, finally.
